if: branch !~ ^appveyor-
language: java
jdk: openjdk11
sudo: false
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    packages:
    - libmagic1
    - libmagic-dev
    - libaio-dev
install: true
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
script:
  - set -e
  - mvn clean install --quiet
