version: '{build}'
image: Visual Studio 2017
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11
branches:
  except:
    - gh-pages
install:
  - cmd: SET MAVEN_OPTS=-Xmx4g
  - cmd: SET JAVA_OPTS=-Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -Dmaven.test.skip=true %MORE_MAVEN_OPTS%
test_script:
  - mvn clean install --batch-mode %MORE_MAVEN_OPTS%
cache:
  - C:\Users\appveyor\.m2
